### ISSUE TITLE
npm registry側のREADMEが表示されない

### ISSUE THREAD

**Issue by kjirou** [kjirou/gakumas-core#131]
- しばらく待てば解決するのかもしれない
- npm registry側にお問い合わせしてとのこと: https://github.com/npm/cli/issues/3904

<img width="824" alt="image" src="https://github.com/user-attachments/assets/de7604ea-bb9f-4f34-867b-5fc9d74d49d6">

**Comment by tada-js** [comment]
こんにちは。私も同じ問題を抱えています。問題は解決されましたか？
- https://github.com/tada-js/react-tada/issues/1

npm CLIに登録された新しいイシューもあります。参考にしてください。
- https://github.com/npm/cli/issues/7711

**Comment by kjirou** [comment]
ありがとうございます！

**Comment by kjirou** [comment]
なるほど...　しばらく待てば良い。
> It's fixed automatically somehow, for future readers - the moral of the story is try to wait 4-5 hrs to see if readme updates.

直っていました！
https://www.npmjs.com/package/gakumas-core
